### ISSUE TITLE
Sett opp client for å hente utenladsadresser fra PDL

### ISSUE THREAD

**Issue by oddgfa** [navikt/utenlandsadresser#5]
```[tasklist]
### Tasks
- [ ] https://github.com/navikt/utenlandsadresser/issues/11
- [x] Kan gjennomføre en tom spørring og få OK 200 tilbake
- [x] https://github.com/navikt/utenlandsadresser/issues/9
- [ ] https://github.com/navikt/utenlandsadresser/issues/8
```
