### ISSUE TITLE
GraphQL-klient mot PDL henter ønsket data om utenlandsadresser

### ISSUE THREAD

**Issue by oddgfa** [navikt/utenlandsadresser#6]
```[tasklist]
### Tasks
- [x] Finn ut hvilke felter vi trenger fra PDL
- [ ] https://github.com/navikt/utenlandsadresser/issues/13
- [ ] https://github.com/navikt/utenlandsadresser/issues/14
```

**Comment by oddgfa** [comment]
Skal ikke gjøres, ref https://github.com/navikt/utenlandsadresser/issues/15
